repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: commit-msg-lint
        name: Conventional Commit (simple)
        entry: python3 scripts/hooks/commit_msg_lint.py
        language: system
        stages: [commit-msg]

# Guard-relative commits (optional; active only if ALLOWED_PATH_PREFIX is set in env)
- repo: local
  hooks:
    - id: path-guard
      name: Path Guard (respects $ALLOWED_PATH_PREFIX)
      entry: python3 scripts/hooks/path_guard.py
      language: system
      stages: [commit]
