# HotDash Shopify App Configuration
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

name = "HotDash"
client_id = "4f72376ea61be956c860dd020552124d"
application_url = "https://hotdash-staging.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "hotroddash.myshopify.com"

[access_scopes]
# Use custom access scopes - defined in Shopify Partners dashboard
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://hotdash-staging.fly.dev/auth/callback",
  "https://hotdash-staging.fly.dev/auth/shopify/callback",
  "https://hotdash-staging.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

[pos]
embedded = false

