# Fly.io configuration for Google Analytics MCP Server
app = "hotdash-analytics-mcp"
primary_region = "ord"

[build]

[env]
  PORT = "8080"
  # GOOGLE_PROJECT_ID will be set via secrets

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
