name: Secret Scan (Gitleaks)
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          version: latest
          args: "detect --redact --config=.github/gitleaks.toml"