app = "hotdash-llm-gateway"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  LANGFUSE_HOST = "https://langfuse.hotrodan.com"

[processes]
  gateway = "/app/bin/start-litellm.sh"
  ui = "/app/bin/start-langfuse.sh"
  worker = "/app/bin/start-langfuse-worker.sh"

[[services]]
  processes = ["gateway"]
  protocol = "tcp"
  internal_port = 4000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

  [[services.http_checks]]
    interval = "30s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    timeout = "5s"

  [[services.concurrency]]
    type = "requests"
    hard_limit = 150
    soft_limit = 120

[[services]]
  processes = ["ui"]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

  [[services.http_checks]]
    interval = "30s"
    grace_period = "45s"
    method = "get"
    path = "/api/health"
    timeout = "5s"

[[vm]]
  memory_mb = 2048
  cpu_kind = "shared"
  cpus = 1

[checks.langfuse-worker]
  type = "tcp"
  port = 3030
  timeout = "5s"
  interval = "30s"
  grace_period = "45s"
  processes = ["worker"]
