app = "hotdash-langfuse-clickhouse"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[env]
  CLICKHOUSE_DB = "langfuse"
  CLICKHOUSE_USER = "langfuse"
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT = 1
  CLICKHOUSE_DEFAULT_LISTEN_HOST = "0.0.0.0"
  CLICKHOUSE_LISTEN_HOST = "0.0.0.0"

[[mounts]]
  source = "langfuse_clickhouse_data"
  destination = "/var/lib/clickhouse"

[[services]]
  protocol = "tcp"
  internal_port = 8123
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 8123

[[services]]
  protocol = "tcp"
  internal_port = 9000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 9000

[checks.tcp]
  type = "tcp"
  port = 9000
  interval = "30s"
  timeout = "5s"
  grace_period = "30s"
