app = "hotdash-langfuse-clickhouse"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  image = "clickhouse/clickhouse-server:24.8"

[env]
  CLICKHOUSE_DB = "langfuse"
  CLICKHOUSE_USER = "langfuse"
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT = 1

[[mounts]]
  source = "langfuse_clickhouse_data"
  destination = "/var/lib/clickhouse"

[[services]]
  protocol = "tcp"
  internal_port = 9000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[checks.tcp]
  type = "tcp"
  port = 9000
  interval = "30s"
  timeout = "5s"
  grace_period = "30s"
