name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-mcp-evidence:
    name: Validate MCP Evidence (PR only)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Validate MCP Evidence in PR body
        run: |
          set -euo pipefail
          echo "Reading PR body from $GITHUB_EVENT_PATH"
          BODY=$(jq -r '.pull_request.body // ""' "$GITHUB_EVENT_PATH")
          echo "$BODY" > pr_body.md
          echo "--- PR BODY START ---"; sed -n '1,120p' pr_body.md; echo "--- PR BODY END ---"
          # Require MCP Evidence section
          echo "$BODY" | grep -qi 'MCP Evidence:' || { echo "❌ Missing 'MCP Evidence:' section in PR body"; exit 1; }
          # Require at least one artifacts path to mcp/*.jsonl
          echo "$BODY" | grep -Eqi 'artifacts/.+/[0-9]{4}-[0-9]{2}-[0-9]{2}/mcp/.+\.jsonl' || { echo "❌ Missing MCP artifact reference (artifacts/<agent>/<date>/mcp/*.jsonl)"; exit 1; }
          echo "✅ MCP evidence present"

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run CI suite
        run: npm run ci
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: artifacts/**/*.xml
          if-no-files-found: ignore

  manager-outcome:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Assert manager produced PR or escalation
        run: ./scripts/manager/assert-outcome.sh
