name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run CI suite
        run: npm run ci
      - name: Dev MCP Ban Check
        run: node scripts/ci/verify-dev-mcp-ban.cjs
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: artifacts/**/*.xml
          if-no-files-found: ignore

  manager-outcome:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Assert manager produced PR or escalation
        run: ./scripts/manager/assert-outcome.sh
