name: Direction Guard
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]
jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate direction change policy
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: node scripts/ci/check-direction-guard.mjs