name: Enforce Database-Driven Workflow

on:
  pull_request:
    branches: [ main, agent-launch-20251022 ]
  push:
    branches: [ main, agent-launch-20251022 ]

jobs:
  enforce-database-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Enforce Database-Driven Process
      run: |
        echo "🔍 ENFORCEMENT: Database-Driven Workflow Compliance"
        echo "=================================================="
        
        # Check for markdown direction file usage
        echo "📋 Checking for markdown direction file usage..."
        if grep -r "docs/directions/" app/ --include="*.ts" --include="*.tsx" | grep -v "archived"; then
          echo "❌ VIOLATION: Agents reading markdown direction files"
          echo "   Action: Use database queries instead of markdown files"
          echo "   Command: npx tsx --env-file=.env scripts/agent/get-my-tasks.ts <agent>"
          exit 1
        fi
        
        # Check for feedback markdown usage (should use logDecision)
        echo "📊 Checking for markdown feedback usage..."
        if grep -r "feedback/.*\.md" app/ --include="*.ts" --include="*.tsx" | grep -v "logDecision"; then
          echo "❌ VIOLATION: Agents using markdown feedback instead of logDecision()"
          echo "   Action: Use logDecision() for all progress reporting"
          echo "   Import: import { logDecision } from '~/services/decisions.server'"
          exit 1
        fi
        
        # Check for database task querying
        echo "🗄️ Checking for database task querying..."
        if ! grep -r "getMyTasks\|get-my-tasks" app/ --include="*.ts" --include="*.tsx"; then
          echo "⚠️ WARNING: No database task querying found"
          echo "   Recommendation: Agents should query tasks from database"
        fi
        
        # Check for logDecision usage
        echo "📈 Checking for logDecision() usage..."
        if ! grep -r "logDecision" app/ --include="*.ts" --include="*.tsx"; then
          echo "❌ VIOLATION: No logDecision() calls found"
          echo "   Action: Agents must log progress via logDecision()"
          echo "   Required: All progress reporting must use database"
          exit 1
        fi
        
        echo "✅ Database-driven workflow compliance verified"
        echo "   - No markdown direction file usage"
        echo "   - No markdown feedback usage"
        echo "   - logDecision() usage detected"
        echo "   - Database-driven process enforced"
