name: Enforce Database-Driven Workflow

on:
  pull_request:
    branches: [ main, agent-launch-20251022, agent-launch-20251024 ]
  push:
    branches: [ main, agent-launch-20251022, agent-launch-20251024 ]

jobs:
  enforce-database-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Determine changed source files
      id: diff
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
      run: |
        git fetch origin $BASE_REF --depth=200
        BASE_SHA=$(git rev-parse origin/$BASE_REF)
        HEAD_SHA=$(git rev-parse HEAD)
        git diff --name-only $BASE_SHA $HEAD_SHA > changed.txt
        grep -E '\.(ts|tsx)$' changed.txt > changed-ts.txt || true
        count=$(wc -l < changed-ts.txt | tr -d ' ')
        echo "count=$count" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Enforce Database-Driven Process
      if: steps.diff.outputs.count != '0'
      run: |
        echo "🔍 ENFORCEMENT: Database-Driven Workflow Compliance"
        echo "=================================================="
        RAW=$(cat changed-ts.txt)
        if [ -z "$RAW" ]; then
          echo "✅ No TypeScript changes detected; skipping enforcement"
          exit 0
        fi

        EXISTING=()
        while IFS= read -r file; do
          [ -z "$file" ] && continue
          if [ -f "$file" ]; then
            EXISTING+=("$file")
          fi
        done <<< "$RAW"

        if [ ${#EXISTING[@]} -eq 0 ]; then
          echo "✅ No existing TypeScript files to scan; skipping enforcement"
          exit 0
        fi

        RECENT=$(git log --since="2025-10-25" --pretty=format:%H -- "${EXISTING[@]}" 2>/dev/null || true)
        if [ -z "$RECENT" ]; then
          echo "✅ Changes pre-date 2025-10-25 guard enforcement; skipping"
          exit 0
        fi

        echo "Files scanned:"
        printf '%s\n' "${EXISTING[@]}"

        echo "📋 Checking for markdown direction file usage..."
        if printf '%s\n' "${EXISTING[@]}" | grep -i 'docs/directions/' | grep -v 'archived' >/dev/null 2>&1; then
          echo "❌ VIOLATION: Agents reading markdown direction files"
          echo "   Action: Use database queries instead of markdown files"
          echo "   Command: npx tsx --env-file=.env scripts/agent/get-my-tasks.ts <agent>"
          exit 1
        fi

        echo "📊 Checking for markdown feedback usage..."
        if grep -i 'feedback/.*\.md' "${EXISTING[@]}" 2>/dev/null | grep -v 'logDecision' >/dev/null 2>&1; then
          echo "❌ VIOLATION: Agents using markdown feedback instead of logDecision()"
          echo "   Action: Use logDecision() for all progress reporting"
          echo "   Import: import { logDecision } from '~/services/decisions.server'"
          exit 1
        fi

        echo "🗄️ Checking for database task querying..."
        if ! printf '%s\n' "${EXISTING[@]}" | grep -i 'getMyTasks\|get-my-tasks' >/dev/null 2>&1 \
          && ! grep -i 'getMyTasks\|get-my-tasks' "${EXISTING[@]}" >/dev/null 2>&1; then
          echo "⚠️ WARNING: No database task querying found"
          echo "   Recommendation: Agents should query tasks from database"
        fi

        echo "📈 Checking for logDecision() usage..."
        if ! grep -qi 'logDecision' "${EXISTING[@]}" 2>/dev/null; then
          echo "❌ VIOLATION: No logDecision() calls found"
          echo "   Action: Agents must log progress via logDecision()"
          echo "   Required: All progress reporting must use database"
          exit 1
        fi

        echo "✅ Database-driven workflow compliance verified"
        echo "   - No markdown direction file usage"
        echo "   - No markdown feedback usage"
        echo "   - logDecision() usage detected"
        echo "   - Database-driven process enforced"

    - name: Skip enforcement (no applicable files)
      if: steps.diff.outputs.count == '0'
      run: |
        echo "✅ No TypeScript changes detected; skipping database workflow enforcement"
