name: Gitleaks (Secrets Scan)
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC
permissions:
  contents: read
  actions: read
  security-events: write
  statuses: write
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install gitleaks
        run: |
          set -euo pipefail
          curl -fsSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz -o gitleaks.tgz
          tar -xzf gitleaks.tgz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version || true
      - name: Run gitleaks
        run: |
          set -euo pipefail
          gitleaks detect \
            --source . \
            --config .gitleaks.toml \
            --baseline-path security/gitleaks-baseline.json \
            --redact \
            --report-format sarif \
            --report-path results.sarif
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with: { sarif_file: results.sarif }
