name: Growth Engine - Inventory Agent (Hourly)

on:
  schedule:
    # Run hourly
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  inventory-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Inventory Agent
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/cron/growth-engine/inventory" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -w "\nHTTP Status: %{http_code}\n" \
            -o response.json
          
          echo "Response:"
          cat response.json
          
          # Check if request was successful
          if [ $(jq -r '.success' response.json) != "true" ]; then
            echo "Inventory agent failed"
            exit 1
          fi
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inventory-agent-results-${{ github.run_id }}
          path: response.json
          retention-days: 7

