name: Guard MCP - Evidence Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  guard-mcp:
    name: Validate MCP Evidence
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check for MCP Evidence in PR
        run: |
          echo "🔍 Checking for MCP Evidence in PR..."
          
          # Check if PR body contains MCP Evidence section
          if ! grep -q "## MCP Evidence" <<< "${{ github.event.pull_request.body }}"; then
            echo "❌ PR body missing '## MCP Evidence' section"
            echo "Required format:"
            echo "## MCP Evidence (required for code changes)"
            echo "- artifacts/<agent>/<date>/mcp/<topic>.jsonl"
            echo "OR"
            echo "- No MCP usage - non-code change"
            exit 1
          fi
          
          # Check if evidence files exist (if not "non-code change")
          if ! grep -q "No MCP usage - non-code change" <<< "${{ github.event.pull_request.body }}"; then
            echo "🔍 Checking for MCP evidence files..."
            
            # Extract file paths from PR body
            EVIDENCE_PATHS=$(grep -A 10 "## MCP Evidence" <<< "${{ github.event.pull_request.body }}" | grep "^- " | sed 's/^- //')
            
            if [ -z "$EVIDENCE_PATHS" ]; then
              echo "❌ No MCP evidence file paths found in PR body"
              exit 1
            fi
            
            # Check if files exist
            MISSING_FILES=()
            while IFS= read -r path; do
              if [ ! -f "$path" ]; then
                MISSING_FILES+=("$path")
              fi
            done <<< "$EVIDENCE_PATHS"
            
            if [ ${#MISSING_FILES[@]} -gt 0 ]; then
              echo "❌ Missing MCP evidence files:"
              printf '%s\n' "${MISSING_FILES[@]}"
              exit 1
            fi
            
            # Validate JSONL format
            while IFS= read -r path; do
              if [ -f "$path" ]; then
                echo "🔍 Validating JSONL format for $path..."
                while IFS= read -r line; do
                  if [ -n "$line" ]; then
                    if ! echo "$line" | jq . > /dev/null 2>&1; then
                      echo "❌ Invalid JSON in $path: $line"
                      exit 1
                    fi
                  fi
                done < "$path"
              fi
            done <<< "$EVIDENCE_PATHS"
          fi
          
          echo "✅ MCP Evidence validation passed"
      
      - name: Report results
        run: |
          echo "✅ MCP Evidence validation completed successfully"
          echo "All required MCP evidence files are present and valid"
