name: idle-guard
on: [pull_request]
jobs:
  idlecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if tasks are 'doing' with no heartbeat in last 15 min
        run: |
          set -e
          FILE=$(git ls-files "artifacts/*/*/tasks.todo.json" | head -n1 || true)
          if [ -z "$FILE" ]; then exit 0; fi
          DOING=$(jq -r '.tasks[] | select(.status=="doing") | .id' "$FILE" || true)
          if [ -z "$DOING" ]; then exit 0; fi
          HB=$(git ls-files "artifacts/*/*/heartbeat.ndjson" | head -n1 || true)
          if [ -z "$HB" ]; then echo "::error::No heartbeat while tasks are doing."; exit 1; fi
          LAST=$(awk 'NF{line=$0} END{print line}' "$HB" | jq -r .ts)
          if [ -z "$LAST" ] || [ "$LAST" = "null" ]; then echo "::error::Invalid heartbeat."; exit 1; fi
          NOW=$(date -u +%s)
          LASTS=$(date -u -d "$LAST" +%s)
          AGE=$(( NOW - LASTS ))
          if [ $AGE -gt 900 ]; then
            echo "::error::Heartbeat older than 15 minutes with tasks 'doing'."; exit 1;
          fi
