name: Infrastructure Monitoring

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Collect Fly.io metrics
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          bash scripts/monitoring/fly-metrics-dashboard.sh || echo "::warning::Some apps unhealthy"

      - name: Upload metrics
        uses: actions/upload-artifact@v4
        with:
          name: fly-metrics-${{ github.run_number }}
          path: artifacts/monitoring
          retention-days: 30

      - name: Create alert issue (on failure)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Infrastructure Alert: ${new Date().toISOString()}`,
              body: `Infrastructure monitoring detected issues.\n\nWorkflow: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              labels: ['infrastructure', 'alert', 'automated']
            })
