name: Nightly Metrics

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  nightly-metrics:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Validate database configuration
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL secret must be configured for nightly metrics" >&2
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Apply Prisma migrations
        run: npx prisma migrate deploy

      - name: Run nightly metrics job
        run: npm run ops:nightly-metrics
