name: Secret Scanning

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  scan-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for comprehensive scan
      
      - name: Run secret scanner
        run: |
          chmod +x scripts/security/scan-secrets.sh
          ./scripts/security/scan-secrets.sh
      
      - name: Upload scan results (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-results
          path: |
            scripts/security/
          retention-days: 30
      
      - name: Comment on PR (if secrets found)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚨 **Secret Scanner Alert**\n\nPotential secrets were detected in this PR. Please review the scan results and remove any exposed credentials.\n\n**Never commit real secrets.** Use environment variables instead.\n\nCheck the workflow logs for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

