name: Security & Secrets
on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: "17 3 * * *"
jobs:
  codeql:
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/owasp-top-ten
            p/r2c-security-audit
          generateSarif: "1"
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: true
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  zap_baseline:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.DEV_TUNNEL_URL || 'http://localhost:3000' }}
          rules_file_name: '.zap/rules.tsv'
        continue-on-error: true
