name: Daily SEO Audit

on:
  schedule:
    # Run daily at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  seo-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
      - name: Run daily SEO audit
        run: npx tsx scripts/seo/daily-audit-cron.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SHOPIFY_SHOP_DOMAIN: ${{ secrets.SHOPIFY_SHOP_DOMAIN }}
          CRON_SECRET_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
          
      - name: Upload audit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: seo-audit-results-${{ github.run_id }}
          path: artifacts/seo/
          retention-days: 30
